"""
crud/messages.py — Message logging, inbox queries, and conversation management.
Covers both the legacy chat_messages table and the newer messages/customers tables.
"""

from __future__ import annotations

import logging
from typing import Optional

from core.db import supabase
from crud._helpers import _now, _one
from crud.customers import get_customer_by_id

log = logging.getLogger(__name__)


# ── Legacy chat_messages ──────────────────────────────────────────────────────

def log_message(business_id: int, phone: str, direction: str, message: str) -> None:
    try:
        supabase.table("chat_messages").insert({
            "business_id": business_id,
            "phone":       phone,
            "direction":   direction,
            "message":     message,
            "created_at":  _now(),
        }).execute()
    except Exception as exc:
        log.error("log_message failed: %s", exc)


def get_conversations(business_id: int) -> list[dict]:
    res = (
        supabase.table("chat_messages")
        .select("*")
        .eq("business_id", business_id)
        .order("id", desc=True)
        .execute()
    )
    rows = res.data or []
    seen: set[str] = set()
    latest: list[dict] = []
    for row in rows:
        if row["phone"] not in seen:
            seen.add(row["phone"])
            latest.append(row)
    return latest


def get_messages_for_phone(business_id: int, phone: str) -> list[dict]:
    res = (
        supabase.table("chat_messages")
        .select("*")
        .eq("business_id", business_id)
        .eq("phone", phone)
        .order("created_at")
        .execute()
    )
    return res.data or []


# ── CRM messages ──────────────────────────────────────────────────────────────

def message_exists(wa_message_id: str) -> bool:
    if not wa_message_id:
        return False
    res = (
        supabase.table("messages")
        .select("id")
        .eq("wa_message_id", wa_message_id)
        .limit(1)
        .execute()
    )
    exists = bool(res.data)
    if exists:
        log.warning("⚠️  Duplicate WA message skipped  wa_id=%s", wa_message_id)
    return exists


def create_message(
    customer_id: int,
    business_id: int,
    text: str,
    direction: str,
    wa_message_id: str | None = None,
    sender_type: str | None = None,
    sender_name: str | None = None,
    agent_id: str | None = None,
) -> dict:
    """
    Save a message to the messages table.

    sender_type differentiates:
      - "ai"    → response generated by the AI assistant
      - "agent" → typed and sent manually by a human agent from the dashboard
      - None    → incoming customer message (direction="incoming")
    """
    is_read = direction == "outgoing"
    row: dict = {
        "customer_id": customer_id,
        "business_id": business_id,
        "text":        text,
        "direction":   direction,
        "is_read":     is_read,
        "status":      "sent",
        "created_at":  _now(),
    }
    if wa_message_id:
        row["wa_message_id"] = wa_message_id

    if sender_type and _has_messages_col("sender_type"):
        row["sender_type"] = sender_type
    if sender_name and _has_messages_col("sender_name"):
        row["sender_name"] = sender_name
    if agent_id and _has_messages_col("agent_id"):
        row["agent_id"] = agent_id

    res = supabase.table("messages").insert(row).execute()
    msg = _one("messages", res)

    if direction == "incoming":
        try:
            supabase.rpc("increment_unread", {"p_customer_id": customer_id}).execute()
        except Exception as exc:
            log.warning("increment_unread rpc failed (customer %s): %s", customer_id, exc)

    return msg


# Cache for messages table columns
_messages_columns: set | None = None


def _has_messages_col(col: str) -> bool:
    """Check if a column exists in the messages table — cached after first call."""
    global _messages_columns
    if _messages_columns is None:
        try:
            res = supabase.table("messages").select("*").limit(1).execute()
            if res.data:
                _messages_columns = set(res.data[0].keys())
            else:
                _messages_columns = {"id", "customer_id", "business_id", "text",
                                     "direction", "is_read", "status", "created_at"}
        except Exception:
            _messages_columns = set()
    return col in _messages_columns


def get_messages_by_customer(
    customer_id: int,
    limit: int = 50,
    offset: int = 0,
) -> list[dict]:
    """
    Return a page of messages for a customer, in chronological order
    (oldest first) — the natural order for rendering a chat history.

    `offset` counts back from the MOST RECENT message: offset=0 is the
    newest page (the latest `limit` messages), offset=limit is the page
    just before that, and so on. This mirrors how the inbox actually
    scrolls — "load older messages" pages backward in time from "now" —
    rather than paging forward from the start of the conversation.

    Fixed 2026-09: previously ordered ascending and ranged from offset 0,
    which returned the OLDEST messages first on a fresh open (see
    get_recent_messages() below, which already had the correct pattern
    and documented this exact bug in its own docstring). Reusing that
    same desc-then-reverse pattern here so opening a conversation shows
    its latest activity instead of the beginning of its history.
    """
    res = (
        supabase.table("messages")
        .select("*")
        .eq("customer_id", customer_id)
        .order("created_at", desc=True)
        .range(offset, offset + limit - 1)
        .execute()
    )
    rows = res.data or []
    return list(reversed(rows))


def get_recent_messages(customer_id: int, limit: int = 6) -> list[dict]:
    """
    Return the last `limit` messages for a customer, in chronological
    order (oldest of the batch first, most recent last) — the natural
    order for reading as "recent conversation so far".

    Added for Phase 2 (services/conversation_context.py): unlike
    get_messages_by_customer() above, which orders ascending with an
    offset for paginated inbox scrolling (oldest-first from the start,
    not from the end), this fetches from the END of the conversation.
    Does not add any new storage — reuses the same `messages` rows
    already written by create_message() for the dashboard inbox.
    """
    if limit <= 0:
        return []
    # "text, direction, created_at" are the only columns guaranteed present
    # on every deployment (see create_message() above — sender_type/
    # sender_name/agent_id are optional, gated by _has_messages_col). A
    # select() naming an optional column that doesn't exist on a given
    # business's schema would error, so this deliberately selects "*" and
    # picks the guaranteed fields back out in Python instead.
    res = (
        supabase.table("messages")
        .select("*")
        .eq("customer_id", customer_id)
        .order("created_at", desc=True)
        .limit(limit)
        .execute()
    )
    rows = res.data or []
    trimmed = [
        {
            "text": r.get("text", ""),
            "direction": r.get("direction", ""),
            "sender_type": r.get("sender_type"),
            "created_at": r.get("created_at"),
        }
        for r in rows
    ]
    return list(reversed(trimmed))


def mark_messages_read(customer_id: int, business_id: int) -> None:
    supabase.table("messages").update({
        "is_read": True,
        "status":  "read",
    }).eq("customer_id", customer_id)\
      .eq("business_id", business_id)\
      .eq("direction", "incoming")\
      .eq("is_read", False)\
      .execute()

    supabase.table("customers").update({"unread_count": 0}).eq("id", customer_id).execute()


def get_chat_conversations(business_id: int, filter_unread: bool = False) -> list[dict]:
    cust_q = (
        supabase.table("customers")
        .select("*")
        .eq("business_id", business_id)
        .order("last_seen", desc=True)
    )
    if filter_unread:
        cust_q = cust_q.gt("unread_count", 0)
    customers = cust_q.execute().data or []

    if not customers:
        return []

    customer_ids = [c["id"] for c in customers]

    # Fetch the latest message per customer_id. A single capped query
    # (`.limit(len(customer_ids) * 5)`) can starve low-volume customers
    # when a few customers have a recent burst of messages — e.g. 3
    # customers with 20 messages each would fill the whole cap for a
    # 10-customer list, leaving the other 7 with no "latest message" at
    # all even though they each have one somewhere further back. To
    # avoid that, page through in bounded chunks, removing customer_ids
    # from the search as soon as their latest message is found, and
    # stop once every customer has a hit or a hard page cap is reached
    # (so this can never turn into an unbounded full-table scan).
    latest: dict[int, dict] = {}
    remaining_ids = list(customer_ids)
    page_size = max(len(customer_ids) * 5, 50)
    max_pages = 10
    for _ in range(max_pages):
        if not remaining_ids:
            break
        # Re-querying with IN restricted to the still-unresolved customers
        # (rather than advancing an offset) means each pass's top page_size
        # rows are no longer crowded out by customers already resolved in
        # an earlier pass — so this converges in a bounded number of passes
        # instead of needing to page deep into a single huge result set.
        msgs_res = (
            supabase.table("messages")
            .select("*")
            .eq("business_id", business_id)
            .in_("customer_id", remaining_ids)
            .order("id", desc=True)
            .limit(page_size)
            .execute()
        )
        msgs = msgs_res.data or []
        if not msgs:
            break
        for m in msgs:
            cid = m["customer_id"]
            if cid not in latest:
                latest[cid] = m
        still_missing = [cid for cid in remaining_ids if cid not in latest]
        if len(still_missing) == len(remaining_ids):
            # This pass found nothing new for anyone still missing —
            # further passes over the same data would just repeat it.
            break
        remaining_ids = still_missing

    # Look up which phones are currently in human_handoff state
    # so the inbox can show the 🔴 Handoff filter and badge correctly.
    handoff_phones = set()
    try:
        cart_res = (
            supabase.table("carts")
            .select("phone, state_data")
            .eq("business_id", business_id)
            .execute()
        )
        for row in (cart_res.data or []):
            sd = row.get("state_data") or {}
            if sd.get("state") == "human_handoff":
                handoff_phones.add(row.get("phone"))
    except Exception as exc:
        log.debug("get_chat_conversations: handoff lookup failed: %s", exc)

    result = []
    for c in customers:
        last  = latest.get(c["id"], {})
        phone = c["phone"]
        result.append({
            "customer_id":     c["id"],
            "phone":           phone,
            "customer_since":  c.get("created_at"),
            "last_seen":       c.get("last_seen"),
            "unread_count":    c.get("unread_count") or 0,
            "last_message":    last.get("text", ""),
            "last_direction":  last.get("direction", ""),
            "last_message_at": last.get("created_at"),
            "last_status":     last.get("status", "sent"),
            "in_handoff":      phone in handoff_phones,
            "handoff_state":   "human_handoff" if phone in handoff_phones else None,
        })

    # Sort by REAL last activity, most recent first. `last_message_at`
    # (computed above from the messages table) is the true activity
    # signal — it moves on incoming AND outgoing/AI messages alike.
    # `last_seen` (falls back here for customers with no messages at
    # all, which shouldn't normally happen but is a safe fallback) only
    # moves on INCOMING messages, so sorting by it alone — the previous
    # behavior — put conversations in the wrong order whenever the
    # business/AI sent the most recent reply.
    result.sort(key=lambda r: r.get("last_message_at") or r.get("last_seen") or "", reverse=True)
    return result


def get_messages_since(business_id: int, hours: float = 720.0, limit: int = 4000) -> list[dict]:
    """
    Every message (incoming AND outgoing) for a business within the last
    `hours` hours (default 30 days), oldest first, capped at `limit` rows.
    Added for Phase 14 (services/conversation_analytics.py) — conversation
    counting and average-response-time pairing both need both directions
    ordered together; nothing else in the codebase needed this shape
    before. Returns [] on any error rather than raising.
    """
    from datetime import datetime, timedelta, timezone
    try:
        cutoff = (datetime.now(timezone.utc) - timedelta(hours=hours)).isoformat()
        res = (
            supabase.table("messages")
            .select("customer_id, text, direction, sender_type, created_at")
            .eq("business_id", business_id)
            .gte("created_at", cutoff)
            .order("created_at")
            .limit(limit)
            .execute()
        )
        return res.data or []
    except Exception as exc:
        log.warning("get_messages_since error  biz=%s  exc=%s", business_id, exc)
        return []


def get_incoming_texts_since(business_id: int, hours: float = 720.0, limit: int = 1000) -> list[str]:
    """
    Just the text of recent incoming customer messages for a business —
    used by Phase 14's lazy re-classification (top questions / unknown-
    intent rate / low-confidence rate). Deliberately returns bare strings,
    not full rows with customer_id/phone, since the analytics this feeds
    only ever reports aggregated counts — never a per-customer breakdown —
    per the "don't expose private customer information unnecessarily"
    requirement. Returns [] on any error.
    """
    from datetime import datetime, timedelta, timezone
    try:
        cutoff = (datetime.now(timezone.utc) - timedelta(hours=hours)).isoformat()
        res = (
            supabase.table("messages")
            .select("text")
            .eq("business_id", business_id)
            .eq("direction", "incoming")
            .gte("created_at", cutoff)
            .order("created_at", desc=True)
            .limit(limit)
            .execute()
        )
        return [r.get("text", "") for r in (res.data or []) if r.get("text")]
    except Exception as exc:
        log.warning("get_incoming_texts_since error  biz=%s  exc=%s", business_id, exc)
        return []


def delete_message(message_id: int, business_id: int) -> bool:
    """
    Delete a single message by id.
    Only deletes messages belonging to the given business.
    Returns True if a row was deleted.
    """
    try:
        res = (
            supabase.table("messages")
            .delete()
            .eq("id", message_id)
            .eq("business_id", business_id)
            .execute()
        )
        deleted = bool(res.data)
        if deleted:
            log.info("delete_message OK  id=%s  business=%s", message_id, business_id)
        return deleted
    except Exception as exc:
        log.error("delete_message error  id=%s  exc=%s", message_id, exc)
        return False


def clear_customer_messages(customer_id: int, business_id: int) -> int:
    """
    Delete all messages for a customer within a business.
    Also resets the customer's unread_count to 0.
    Returns the number of rows deleted.
    """
    try:
        res = (
            supabase.table("messages")
            .delete()
            .eq("customer_id", customer_id)
            .eq("business_id", business_id)
            .execute()
        )
        count = len(res.data) if res.data else 0

        # Also clear legacy chat_messages table for same phone
        try:
            cust = get_customer_by_id(customer_id, business_id)
            if cust:
                supabase.table("chat_messages") \
                    .delete() \
                    .eq("business_id", business_id) \
                    .eq("phone", cust["phone"]) \
                    .execute()
        except Exception:
            pass

        # Reset unread badge
        supabase.table("customers") \
            .update({"unread_count": 0}) \
            .eq("id", customer_id) \
            .execute()

        log.info("clear_customer_messages  customer=%s  deleted=%d", customer_id, count)
        return count
    except Exception as exc:
        log.error("clear_customer_messages error  customer=%s  exc=%s", customer_id, exc)
        return 0
