"""
crud/messages.py — Message logging, inbox queries, and conversation management.
Covers both the legacy chat_messages table and the newer messages/customers tables.
"""

from __future__ import annotations

import logging
from typing import Optional

from core.db import supabase
from crud._helpers import _now, _one
from crud.customers import get_customer_by_id

log = logging.getLogger(__name__)


# ── Legacy chat_messages ──────────────────────────────────────────────────────

def log_message(business_id: int, phone: str, direction: str, message: str) -> None:
    try:
        supabase.table("chat_messages").insert({
            "business_id": business_id,
            "phone":       phone,
            "direction":   direction,
            "message":     message,
            "created_at":  _now(),
        }).execute()
    except Exception as exc:
        log.error("log_message failed: %s", exc)


def get_conversations(business_id: int) -> list[dict]:
    res = (
        supabase.table("chat_messages")
        .select("*")
        .eq("business_id", business_id)
        .order("id", desc=True)
        .execute()
    )
    rows = res.data or []
    seen: set[str] = set()
    latest: list[dict] = []
    for row in rows:
        if row["phone"] not in seen:
            seen.add(row["phone"])
            latest.append(row)
    return latest


def get_messages_for_phone(business_id: int, phone: str) -> list[dict]:
    res = (
        supabase.table("chat_messages")
        .select("*")
        .eq("business_id", business_id)
        .eq("phone", phone)
        .order("created_at")
        .execute()
    )
    return res.data or []


# ── CRM messages ──────────────────────────────────────────────────────────────

def message_exists(wa_message_id: str) -> bool:
    if not wa_message_id:
        return False
    res = (
        supabase.table("messages")
        .select("id")
        .eq("wa_message_id", wa_message_id)
        .limit(1)
        .execute()
    )
    exists = bool(res.data)
    if exists:
        log.warning("⚠️  Duplicate WA message skipped  wa_id=%s", wa_message_id)
    return exists


def create_message(
    customer_id: int,
    business_id: int,
    text: str,
    direction: str,
    wa_message_id: str | None = None,
    sender_type: str | None = None,
    sender_name: str | None = None,
) -> dict:
    """
    Save a message to the messages table.

    sender_type differentiates:
      - "ai"    → response generated by the AI assistant
      - "agent" → typed and sent manually by a human agent from the dashboard
      - None    → incoming customer message (direction="incoming")
    """
    is_read = direction == "outgoing"
    row: dict = {
        "customer_id": customer_id,
        "business_id": business_id,
        "text":        text,
        "direction":   direction,
        "is_read":     is_read,
        "status":      "sent",
        "created_at":  _now(),
    }
    if wa_message_id:
        row["wa_message_id"] = wa_message_id

    if sender_type and _has_messages_col("sender_type"):
        row["sender_type"] = sender_type
    if sender_name and _has_messages_col("sender_name"):
        row["sender_name"] = sender_name

    res = supabase.table("messages").insert(row).execute()
    msg = _one("messages", res)

    if direction == "incoming":
        try:
            supabase.rpc("increment_unread", {"p_customer_id": customer_id}).execute()
        except Exception as exc:
            log.warning("increment_unread rpc failed (customer %s): %s", customer_id, exc)

    return msg


# Cache for messages table columns
_messages_columns: set | None = None


def _has_messages_col(col: str) -> bool:
    """Check if a column exists in the messages table — cached after first call."""
    global _messages_columns
    if _messages_columns is None:
        try:
            res = supabase.table("messages").select("*").limit(1).execute()
            if res.data:
                _messages_columns = set(res.data[0].keys())
            else:
                _messages_columns = {"id", "customer_id", "business_id", "text",
                                     "direction", "is_read", "status", "created_at"}
        except Exception:
            _messages_columns = set()
    return col in _messages_columns


def get_messages_by_customer(
    customer_id: int,
    limit: int = 50,
    offset: int = 0,
) -> list[dict]:
    res = (
        supabase.table("messages")
        .select("*")
        .eq("customer_id", customer_id)
        .order("created_at")
        .range(offset, offset + limit - 1)
        .execute()
    )
    return res.data or []


def mark_messages_read(customer_id: int, business_id: int) -> None:
    supabase.table("messages").update({
        "is_read": True,
        "status":  "read",
    }).eq("customer_id", customer_id)\
      .eq("business_id", business_id)\
      .eq("direction", "incoming")\
      .eq("is_read", False)\
      .execute()

    supabase.table("customers").update({"unread_count": 0}).eq("id", customer_id).execute()


def get_chat_conversations(business_id: int, filter_unread: bool = False) -> list[dict]:
    cust_q = (
        supabase.table("customers")
        .select("*")
        .eq("business_id", business_id)
        .order("last_seen", desc=True)
    )
    if filter_unread:
        cust_q = cust_q.gt("unread_count", 0)
    customers = cust_q.execute().data or []

    if not customers:
        return []

    customer_ids = [c["id"] for c in customers]

    msgs_res = (
        supabase.table("messages")
        .select("*")
        .eq("business_id", business_id)
        .in_("customer_id", customer_ids)
        .order("id", desc=True)
        .limit(len(customer_ids) * 5)
        .execute()
    )
    msgs = msgs_res.data or []

    latest: dict[int, dict] = {}
    for m in msgs:
        cid = m["customer_id"]
        if cid not in latest:
            latest[cid] = m

    result = []
    for c in customers:
        last = latest.get(c["id"], {})
        result.append({
            "customer_id":     c["id"],
            "phone":           c["phone"],
            "customer_since":  c.get("created_at"),
            "last_seen":       c.get("last_seen"),
            "unread_count":    c.get("unread_count") or 0,
            "last_message":    last.get("text", ""),
            "last_direction":  last.get("direction", ""),
            "last_message_at": last.get("created_at"),
            "last_status":     last.get("status", "sent"),
        })
    return result


def delete_message(message_id: int, business_id: int) -> bool:
    """
    Delete a single message by id.
    Only deletes messages belonging to the given business.
    Returns True if a row was deleted.
    """
    try:
        res = (
            supabase.table("messages")
            .delete()
            .eq("id", message_id)
            .eq("business_id", business_id)
            .execute()
        )
        deleted = bool(res.data)
        if deleted:
            log.info("delete_message OK  id=%s  business=%s", message_id, business_id)
        return deleted
    except Exception as exc:
        log.error("delete_message error  id=%s  exc=%s", message_id, exc)
        return False


def clear_customer_messages(customer_id: int, business_id: int) -> int:
    """
    Delete all messages for a customer within a business.
    Also resets the customer's unread_count to 0.
    Returns the number of rows deleted.
    """
    try:
        res = (
            supabase.table("messages")
            .delete()
            .eq("customer_id", customer_id)
            .eq("business_id", business_id)
            .execute()
        )
        count = len(res.data) if res.data else 0

        # Also clear legacy chat_messages table for same phone
        try:
            cust = get_customer_by_id(customer_id, business_id)
            if cust:
                supabase.table("chat_messages") \
                    .delete() \
                    .eq("business_id", business_id) \
                    .eq("phone", cust["phone"]) \
                    .execute()
        except Exception:
            pass

        # Reset unread badge
        supabase.table("customers") \
            .update({"unread_count": 0}) \
            .eq("id", customer_id) \
            .execute()

        log.info("clear_customer_messages  customer=%s  deleted=%d", customer_id, count)
        return count
    except Exception as exc:
        log.error("clear_customer_messages error  customer=%s  exc=%s", customer_id, exc)
        return 0
